package com.quicktrim.ai.network

object Dummy {
    const val response = "{\n" +
            "\t\"language_code\": \"eng\",\n" +
            "\t\"language_probability\": 0.9716506600379944,\n" +
            "\t\"text\": \"So, o- do you immediately see the inf- effects of this? So, for example, if I, if I go on a run- Yeah. ... am I gonna see increased nitric oxide? Or if I-\",\n" +
            "\t\"words\": [{\n" +
            "\t\t\"text\": \"So,\",\n" +
            "\t\t\"start\": 0.199,\n" +
            "\t\t\"end\": 0.539,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 0.539,\n" +
            "\t\t\"end\": 1.379,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"o-\",\n" +
            "\t\t\"start\": 1.379,\n" +
            "\t\t\"end\": 1.399,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 1.399,\n" +
            "\t\t\"end\": 1.399,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"do\",\n" +
            "\t\t\"start\": 1.399,\n" +
            "\t\t\"end\": 1.539,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 1.539,\n" +
            "\t\t\"end\": 1.559,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"you\",\n" +
            "\t\t\"start\": 1.559,\n" +
            "\t\t\"end\": 1.639,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 1.639,\n" +
            "\t\t\"end\": 1.659,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"immediately\",\n" +
            "\t\t\"start\": 1.659,\n" +
            "\t\t\"end\": 2.119,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 2.119,\n" +
            "\t\t\"end\": 2.2,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"see\",\n" +
            "\t\t\"start\": 2.2,\n" +
            "\t\t\"end\": 2.359,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 2.359,\n" +
            "\t\t\"end\": 2.359,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"the\",\n" +
            "\t\t\"start\": 2.359,\n" +
            "\t\t\"end\": 2.439,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 2.439,\n" +
            "\t\t\"end\": 2.48,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"inf-\",\n" +
            "\t\t\"start\": 2.48,\n" +
            "\t\t\"end\": 2.759,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 2.759,\n" +
            "\t\t\"end\": 2.759,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"effects\",\n" +
            "\t\t\"start\": 2.759,\n" +
            "\t\t\"end\": 3.139,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 3.139,\n" +
            "\t\t\"end\": 3.159,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"of\",\n" +
            "\t\t\"start\": 3.159,\n" +
            "\t\t\"end\": 3.239,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 3.239,\n" +
            "\t\t\"end\": 3.259,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"this?\",\n" +
            "\t\t\"start\": 3.259,\n" +
            "\t\t\"end\": 3.399,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 3.399,\n" +
            "\t\t\"end\": 3.419,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"So,\",\n" +
            "\t\t\"start\": 3.419,\n" +
            "\t\t\"end\": 3.599,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 3.599,\n" +
            "\t\t\"end\": 3.599,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"for\",\n" +
            "\t\t\"start\": 3.599,\n" +
            "\t\t\"end\": 3.719,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 3.719,\n" +
            "\t\t\"end\": 3.74,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"example,\",\n" +
            "\t\t\"start\": 3.74,\n" +
            "\t\t\"end\": 4.079,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 4.079,\n" +
            "\t\t\"end\": 4.079,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"if\",\n" +
            "\t\t\"start\": 4.079,\n" +
            "\t\t\"end\": 4.199,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 4.199,\n" +
            "\t\t\"end\": 4.199,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"I,\",\n" +
            "\t\t\"start\": 4.199,\n" +
            "\t\t\"end\": 4.379,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 4.379,\n" +
            "\t\t\"end\": 4.44,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"if\",\n" +
            "\t\t\"start\": 4.44,\n" +
            "\t\t\"end\": 4.539,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 4.539,\n" +
            "\t\t\"end\": 4.539,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"I\",\n" +
            "\t\t\"start\": 4.539,\n" +
            "\t\t\"end\": 4.659,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 4.659,\n" +
            "\t\t\"end\": 4.759,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"go\",\n" +
            "\t\t\"start\": 4.759,\n" +
            "\t\t\"end\": 4.919,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 4.919,\n" +
            "\t\t\"end\": 4.92,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"on\",\n" +
            "\t\t\"start\": 4.92,\n" +
            "\t\t\"end\": 5.059,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 5.059,\n" +
            "\t\t\"end\": 5.079,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"a\",\n" +
            "\t\t\"start\": 5.079,\n" +
            "\t\t\"end\": 5.199,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 5.199,\n" +
            "\t\t\"end\": 5.199,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"run-\",\n" +
            "\t\t\"start\": 5.199,\n" +
            "\t\t\"end\": 5.52,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 5.52,\n" +
            "\t\t\"end\": 5.779,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"Yeah.\",\n" +
            "\t\t\"start\": 5.779,\n" +
            "\t\t\"end\": 6.04,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_1\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 6.04,\n" +
            "\t\t\"end\": 6.04,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_1\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"...\",\n" +
            "\t\t\"start\": 6.04,\n" +
            "\t\t\"end\": 6.159,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 6.159,\n" +
            "\t\t\"end\": 6.159,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"am\",\n" +
            "\t\t\"start\": 6.159,\n" +
            "\t\t\"end\": 6.279,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 6.279,\n" +
            "\t\t\"end\": 6.299,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"I\",\n" +
            "\t\t\"start\": 6.299,\n" +
            "\t\t\"end\": 6.419,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 6.419,\n" +
            "\t\t\"end\": 6.42,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"gonna\",\n" +
            "\t\t\"start\": 6.42,\n" +
            "\t\t\"end\": 6.659,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 6.659,\n" +
            "\t\t\"end\": 6.699,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"see\",\n" +
            "\t\t\"start\": 6.699,\n" +
            "\t\t\"end\": 6.939,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 6.939,\n" +
            "\t\t\"end\": 6.94,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"increased\",\n" +
            "\t\t\"start\": 6.94,\n" +
            "\t\t\"end\": 7.519,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 7.519,\n" +
            "\t\t\"end\": 7.619,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"nitric\",\n" +
            "\t\t\"start\": 7.619,\n" +
            "\t\t\"end\": 7.999,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 7.999,\n" +
            "\t\t\"end\": 8.039,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"oxide?\",\n" +
            "\t\t\"start\": 8.039,\n" +
            "\t\t\"end\": 8.619,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 8.619,\n" +
            "\t\t\"end\": 8.619,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"Or\",\n" +
            "\t\t\"start\": 8.619,\n" +
            "\t\t\"end\": 8.739,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 8.739,\n" +
            "\t\t\"end\": 8.76,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"if\",\n" +
            "\t\t\"start\": 8.76,\n" +
            "\t\t\"end\": 8.88,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \" \",\n" +
            "\t\t\"start\": 8.88,\n" +
            "\t\t\"end\": 8.96,\n" +
            "\t\t\"type\": \"spacing\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}, {\n" +
            "\t\t\"text\": \"I-\",\n" +
            "\t\t\"start\": 8.96,\n" +
            "\t\t\"end\": 9.039,\n" +
            "\t\t\"type\": \"word\",\n" +
            "\t\t\"speaker_id\": \"speaker_0\",\n" +
            "\t\t\"logprob\": 0.0,\n" +
            "\t\t\"characters\": null\n" +
            "\t}],\n" +
            "\t\"additional_formats\": [{\n" +
            "\t\t\"requested_format\": \"segmented_json\",\n" +
            "\t\t\"file_extension\": \"json\",\n" +
            "\t\t\"content_type\": \"application/json\",\n" +
            "\t\t\"is_base64_encoded\": false,\n" +
            "\t\t\"content\": \"{\\n  \\\"segments\\\": [\\n    {\\n      \\\"text\\\": \\\"So, o- do you immediately see the inf- effects of this?\\\",\\n      \\\"words\\\": [\\n        {\\n          \\\"text\\\": \\\"So,\\\",\\n          \\\"start\\\": 0.199,\\n          \\\"end\\\": 0.539,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 0.539,\\n          \\\"end\\\": 1.379,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"o-\\\",\\n          \\\"start\\\": 1.379,\\n          \\\"end\\\": 1.399,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 1.399,\\n          \\\"end\\\": 1.399,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"do\\\",\\n          \\\"start\\\": 1.399,\\n          \\\"end\\\": 1.539,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 1.539,\\n          \\\"end\\\": 1.559,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"you\\\",\\n          \\\"start\\\": 1.559,\\n          \\\"end\\\": 1.639,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 1.639,\\n          \\\"end\\\": 1.659,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"immediately\\\",\\n          \\\"start\\\": 1.659,\\n          \\\"end\\\": 2.119,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 2.119,\\n          \\\"end\\\": 2.2,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"see\\\",\\n          \\\"start\\\": 2.2,\\n          \\\"end\\\": 2.359,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 2.359,\\n          \\\"end\\\": 2.359,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"the\\\",\\n          \\\"start\\\": 2.359,\\n          \\\"end\\\": 2.439,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 2.439,\\n          \\\"end\\\": 2.48,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"inf-\\\",\\n          \\\"start\\\": 2.48,\\n          \\\"end\\\": 2.759,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 2.759,\\n          \\\"end\\\": 2.759,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"effects\\\",\\n          \\\"start\\\": 2.759,\\n          \\\"end\\\": 3.139,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 3.139,\\n          \\\"end\\\": 3.159,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"of\\\",\\n          \\\"start\\\": 3.159,\\n          \\\"end\\\": 3.239,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 3.239,\\n          \\\"end\\\": 3.259,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"this?\\\",\\n          \\\"start\\\": 3.259,\\n          \\\"end\\\": 3.399,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        }\\n      ]\\n    },\\n    {\\n      \\\"text\\\": \\\"So, for example, if I, if I go on a run-\\\",\\n      \\\"words\\\": [\\n        {\\n          \\\"text\\\": \\\"So,\\\",\\n          \\\"start\\\": 3.419,\\n          \\\"end\\\": 3.599,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 3.599,\\n          \\\"end\\\": 3.599,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"for\\\",\\n          \\\"start\\\": 3.599,\\n          \\\"end\\\": 3.719,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 3.719,\\n          \\\"end\\\": 3.74,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"example,\\\",\\n          \\\"start\\\": 3.74,\\n          \\\"end\\\": 4.079,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 4.079,\\n          \\\"end\\\": 4.079,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"if\\\",\\n          \\\"start\\\": 4.079,\\n          \\\"end\\\": 4.199,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 4.199,\\n          \\\"end\\\": 4.199,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"I,\\\",\\n          \\\"start\\\": 4.199,\\n          \\\"end\\\": 4.379,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 4.379,\\n          \\\"end\\\": 4.44,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"if\\\",\\n          \\\"start\\\": 4.44,\\n          \\\"end\\\": 4.539,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 4.539,\\n          \\\"end\\\": 4.539,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"I\\\",\\n          \\\"start\\\": 4.539,\\n          \\\"end\\\": 4.659,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 4.659,\\n          \\\"end\\\": 4.759,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"go\\\",\\n          \\\"start\\\": 4.759,\\n          \\\"end\\\": 4.919,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 4.919,\\n          \\\"end\\\": 4.92,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"on\\\",\\n          \\\"start\\\": 4.92,\\n          \\\"end\\\": 5.059,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 5.059,\\n          \\\"end\\\": 5.079,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"a\\\",\\n          \\\"start\\\": 5.079,\\n          \\\"end\\\": 5.199,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 5.199,\\n          \\\"end\\\": 5.199,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"run-\\\",\\n          \\\"start\\\": 5.199,\\n          \\\"end\\\": 5.52,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        }\\n      ]\\n    },\\n    {\\n      \\\"text\\\": \\\"Yeah.\\\",\\n      \\\"words\\\": [\\n        {\\n          \\\"text\\\": \\\"Yeah.\\\",\\n          \\\"start\\\": 5.779,\\n          \\\"end\\\": 6.04,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_1\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        }\\n      ]\\n    },\\n    {\\n      \\\"text\\\": \\\"... am I gonna see increased nitric oxide?\\\",\\n      \\\"words\\\": [\\n        {\\n          \\\"text\\\": \\\"...\\\",\\n          \\\"start\\\": 6.04,\\n          \\\"end\\\": 6.159,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 6.159,\\n          \\\"end\\\": 6.159,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"am\\\",\\n          \\\"start\\\": 6.159,\\n          \\\"end\\\": 6.279,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 6.279,\\n          \\\"end\\\": 6.299,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"I\\\",\\n          \\\"start\\\": 6.299,\\n          \\\"end\\\": 6.419,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 6.419,\\n          \\\"end\\\": 6.42,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"gonna\\\",\\n          \\\"start\\\": 6.42,\\n          \\\"end\\\": 6.659,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 6.659,\\n          \\\"end\\\": 6.699,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"see\\\",\\n          \\\"start\\\": 6.699,\\n          \\\"end\\\": 6.939,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 6.939,\\n          \\\"end\\\": 6.94,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"increased\\\",\\n          \\\"start\\\": 6.94,\\n          \\\"end\\\": 7.519,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 7.519,\\n          \\\"end\\\": 7.619,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"nitric\\\",\\n          \\\"start\\\": 7.619,\\n          \\\"end\\\": 7.999,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 7.999,\\n          \\\"end\\\": 8.039,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"oxide?\\\",\\n          \\\"start\\\": 8.039,\\n          \\\"end\\\": 8.619,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        }\\n      ]\\n    },\\n    {\\n      \\\"text\\\": \\\"Or if I-\\\",\\n      \\\"words\\\": [\\n        {\\n          \\\"text\\\": \\\"Or\\\",\\n          \\\"start\\\": 8.619,\\n          \\\"end\\\": 8.739,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 8.739,\\n          \\\"end\\\": 8.76,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"if\\\",\\n          \\\"start\\\": 8.76,\\n          \\\"end\\\": 8.88,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\" \\\",\\n          \\\"start\\\": 8.88,\\n          \\\"end\\\": 8.96,\\n          \\\"type\\\": \\\"spacing\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        },\\n        {\\n          \\\"text\\\": \\\"I-\\\",\\n          \\\"start\\\": 8.96,\\n          \\\"end\\\": 9.039,\\n          \\\"type\\\": \\\"word\\\",\\n          \\\"speaker_id\\\": \\\"speaker_0\\\",\\n          \\\"logprob\\\": 0.0,\\n          \\\"characters\\\": null\\n        }\\n      ]\\n    }\\n  ]\\n}\"\n" +
            "\t}]\n" +
            "}"
}